FROM ubuntu:bionic-20210827

LABEL maintainer="Amin Vakil <info@aminvakil.com>"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       systemd \
       sudo \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

ENTRYPOINT ["/bin/systemd"]
