FROM debian:buster-20210902

LABEL maintainer="Amin Vakil <info@aminvakil.com>"

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    systemd \
    sudo \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc && rm -rf /usr/share/man \
    && apt-get clean

ENTRYPOINT ["/bin/systemd"]
